### ISSUE TITLE
Some additional test ideas- malformed alphabets

### ISSUE THREAD

**Issue by mwdavis2** [seguid/seguid-tests#10]
# an alphabet specification that isn't found
@test "<CLI call> --alphabet='{dna}'  <<< 'ACGT'" {
     run "${cli_call[@]}" --alphabet='{dna}'  <<< 'ACGT'
    assert_failure
}
# a typo in the alphabet list (extra space)
@test "<CLI call> --alphabet='A,G ,C,T'  <<< 'ACGT'" {
     run "${cli_call[@]}" --alphabet='A,G ,C,T'  <<< 'ACGT'
    assert_failure
}
# only one strand specified for double-stranded type
@test "<CLI call>  --type=ldseguid <<< 'AATTA'" {
     run "${cli_call[@]}"  --type=ldseguid <<< 'AATTA'
    assert_failure
}
# a single-stranded alphabet for a double-stranded sequence
@test "<CLI call> --type=ldseguid --alphabet='A,G,C,T'  <<< 'ACGT;ACGT'" {
     run "${cli_call[@]}" --type=ldseguid --alphabet='A,G,C,T'  <<< 'ACGT;ACGT'
    assert_failure
}

**Comment by HenrikBengtsson** [comment]
This looks good to me. Feel free to add these to <https://github.com/seguid/seguid-tests/blob/main/tests/cli.bats>.  Note there are already some "Exception" sections, so see if they fit in one of those. After committing & pushing, keep an eye on the Actions tab to make sure your additions behave as expected.

PS. Take a look at https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code how to put code in a code block in issues and comments. You can edit your own existing comments too.

**Comment by HenrikBengtsson** [comment]
I've added these to the current test suite, cf. commit b48f7a3.
