### ISSUE TITLE
lots of wrong tests? direction of crick sequence

### ISSUE THREAD

**Issue by louisabraham** [seguid/seguid-tests#7]
```
@test "<CLI call> --type=ldseguid --alphabet='{DNA},m1,1m,h2,2h,f3,3f,c4,4c' <<< \$'AmT2C\nT1AhG'" {
    run "${cli_call[@]}" --type=ldseguid --alphabet="{DNA},m1,1m,h2,2h,f3,3f,c4,4c" <<< $'AmT2C\nT1AhG'
    assert_success
    assert_output "ldseguid=bFZedILTms4ORUi3SSMfU0FUl7Q"
}
```

The test takes 

```
AmT2C
T1AhG
```

as input.

I think the correct tests should take
```
AmT2C
GhA1T
```

as input.

This also means that the other implementations are probably wrong.

**Comment by HenrikBengtsson** [comment]
No. See https://github.com/seguid/seguid-javascript/issues/2

**Comment by louisabraham** [comment]
Oh ok. I think this behavior should be explained in the specs.

**Comment by HenrikBengtsson** [comment]
> Oh ok. I think this behavior should be explained in the specs.

Agree. I don't think it needs to be mentioned in the manuscript (we're intentionally very vague on code/API there), but definitely in **seguid-tests** and in the `--help` output and docs.  Having examples of the two types of input will definitely also help clarify the difference.  FWIW, I anticipate we're having a new navbar menu 'Articles' or 'Case Studies' or something on https://www.seguid.org that will have short go-to real-world examples of using SEGUID v2 for proteins, circular dsDNA, ...
