### ISSUE TITLE
Should option --form="both" return two lines?

### ISSUE THREAD

**Issue by louisabraham** [seguid/seguid-tests#8]
instead of separating the checksums by a space

To be discussed

**Comment by HenrikBengtsson** [comment]
I thought about that too, and it's not set in stone.  The current behavior was with batch processing in mind, where you probably want one output line per input sequence.

**Comment by BjornFJohansson** [comment]
I think a tuple with two strings should be returned. Will this cause problems on the command line? We say this in docs already.

R:

https://seguid-r.seguid.org/reference/seguid.html#value:~:text=If%20form%20is%20%22both%22%2C%20then%20a%20character%20vector%20of%20length%20two%20is%20return%2C%20where%20the%20first%20component%20holds%20the%20%22short%22%20checksum%20and%20the%20second%20the%20%22long%22%20checksum.

Python:

https://seguid-python.seguid.org/#:~:text=If%20form%20is%20%E2%80%9Cboth%E2%80%9D%2C%20then%20a%20tuple%20of%20length%20two%20is%20returned%2C%20where%20the%20first%20component%20holds%20the%20%E2%80%9Cshort%E2%80%9D%20checksum%20and%20the%20second%20the%20%E2%80%9Clong%E2%80%9D%20checksum.

or do we change in the docs?

**Comment by HenrikBengtsson** [comment]
@BjornFJohansson misunderstood this issue; we've moved his discussion to https://github.com/seguid/seguid-python/issues/25.

**Comment by HenrikBengtsson** [comment]
I'll make the decision here and now that all output of CLI seguid should be a single line, which means `--form=both` should also output on one line.

closing ...
